import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Subheader from '../components/Subheader'
import Hero from '../components/Hero'
import Footer from '../components/Footer'

export default function Cart() {
  return (
    <div>
      <Head>
        <title>Boudreaux </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Subheader />
      <Header />
      <main className="bg-gray-900 text-white h-screen w-screen">
        <h1 className="font-cinzel text-xl md:text-3xl p-10 text-center align-center justify-center">Cart</h1>
      </main>
      <Footer />
    </div>
  )
}
