import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="bg-black text-white h-screen">
        <h1 className="font-italiana">Boudreaux Couture</h1>
        <h2 className="font-italiana">Jewels from the Heart of Texas </h2>
        <p className="font-robot">Est 2022</p>
        <Hero />
      </main>
      <Footer />
    </div>
  )
}
