import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="font-italiana">Boudreaux Couture</h1>
        <h2 className="font-italiana">Hill Country, Texas || Est 2022 </h2>

      </main>
    </div>
  )
}
