import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Subheader from '../components/Subheader'
import Bestsellers from '../components/Bestsellers'
import Curated from '../components/Curated'
import Footer from '../components/Footer'
import Mailing from '../components/Mailing'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Boudreaux </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Subheader />
      <Header />
      <main className="bg-black text-white h-full w-screen">
        <Hero />
        <Bestsellers />
        <Curated />
        <Mailing />
      </main>
      <Footer />
    </div>
  )
}
